INSERT INTO `c_live_id_config` VALUES (1, 'ds_ag_live', 2, 21, 'AG视讯', 0, 'game_kind', 'bet_time', 'bet_amount', 'valid_bet_amount', 'net_amount', NULL);
INSERT INTO `c_live_id_config` VALUES (2, 'ds_ag_live', 2, 22, 'AG机率', 0, 'game_kind', 'bet_time', 'bet_amount', 'valid_bet_amount', 'net_amount', NULL);
INSERT INTO `c_live_id_config` VALUES (3, 'ds_bbin_3d', 11, 15, 'BBIN 3D', 0, '', 'wagers_date', 'bet_amount', 'commissionable', 'pay_off', NULL);
INSERT INTO `c_live_id_config` VALUES (4, 'ds_bbin_jilv', 11, 5, 'BBIN机率', 0, NULL, 'wagers_date', 'bet_amount', 'commissionable', 'pay_off', NULL);
INSERT INTO `c_live_id_config` VALUES (5, 'ds_bbin_live', 11, 3, 'BBIN视讯', 0, NULL, 'wagers_date', 'bet_amount', 'commissionable', 'pay_off', NULL);
INSERT INTO `c_live_id_config` VALUES (6, 'ds_bbin_sport', 11, 1, 'BBIN体育', 0, NULL, 'wagers_date', 'bet_amount', 'commissionable', 'pay_off', NULL);
INSERT INTO `c_live_id_config` VALUES (7, 'ds_live', 12, 41, 'DS视讯', 0, NULL, 'end_time', 'stake_amount', 'valid_stake', 'win_loss', NULL);
INSERT INTO `c_live_id_config` VALUES (8, 'ds_lottery_bet', 12, 55, 'DS传统彩', 0, NULL, 'bet_time', 'stake_amount', 'valid_stake', 'win_loss', NULL);
INSERT INTO `c_live_id_config` VALUES (9, 'ds_lotto_bet', 12, 54, 'DS香港彩', 0, NULL, 'bet_time', 'stake_amount', 'valid_stake', 'win_loss', NULL);
INSERT INTO `c_live_id_config` VALUES (10, 'ds_fenfen_lotto', 12, 52, 'DS分分彩', 1, NULL, 'bet_time', 'bet_amount', 'valid_amount', 'pay_off', NULL);
INSERT INTO `c_live_id_config` VALUES (11, 'ds_m8_sport', 13, 42, 'H8体育', 1, NULL, 'transaction_date', 'bet_amount', 'commission_amount', 'win_amount', NULL);
INSERT INTO `c_live_id_config` VALUES (12, 'ds_og_record', 3, 23, 'OG视讯', 0, 'game_name_id', 'add_time', 'betting_amount', 'valid_amount', 'win_lose_amount', NULL);
